cv_generator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path(_('resumes/'), include('resumes.urls', namespace="Resumes")),
    path('letters/', include('letters.urls', namespace="Letters")),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

letters/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "letters"

urlpatterns = [
    path('letters/', views.letters, name='create_letters'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resumes/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.utils.translation import gettext_lazy as _

app_name = "resumes"

urlpatterns = [
    path(_('create/'), views.create_cv, name='create_cv'),
    path('ai-profile/', views.ai_profile, name='ai_profile'),
    path('ai-skills/', views.get_skills_ai, name='get_skills'),
    path('ai-edu-desc/', views.ai_education_description, name='ai_eductaion_desc'),
    path('ai-exp-desc/', views.ai_experience_description, name='ai_experience_desc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resumes/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class CVForm(forms.Form):
    poste = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "e.g: Enseignant", "class": "form-control"}),
        max_length=200,
        label=_("Post Title")
    )
    profile_image = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"class": "form-control"}),
        label=_("Profile Image"),
        required=False
    )

    # ---- First, Last name
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "First name", "class": "form-control"}),
        max_length=200,
        label=_("Name")
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Last Name", "class": "form-control"}),
        max_length=200,
        label=_("Last name")
    )

    # ---- Email Phone
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Enter Email Address', "class": "form-control"}),
        label=_("Email")
    )
    phone = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Enter Phone Number'}),
        max_length=20,
        label=_("Phone")
    )

    # -- Ville, Paye
    ville = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter your address', "class": "form-control"}),
        max_length=200,
        label=_("City")
    )
    paye = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Your Country', "class": "form-control"}),
        max_length=200,
        label=_("Country")
    )

    # -- Address, CodePostal
    address = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Address', "class": "form-control"}),
        max_length=200,
        label=_('Address'),
        required=False)

    code_postal = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Code Postal', "class": "form-control"}),
        max_length=100,
        label=_('Postal Code'),
        required=False
    )

    # -- Situation Familiale, Permis
    sit_family = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Situation Familiale", "class": "form-control"}),
        max_length=200,
        label=_("Family Situation"),
        required=False
    )
    permis = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'e.g Permis B', "class": "form-control"}),
        max_length=100,
        label=_('Driving License'),
        required=False
    )

    # -- D.Naissance, Profile
    d_naissance = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', "class": "form-control"}),
        label=_('Date of Birth'),
        required=False
    )
    profile = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "Your Resume", "rows": 5, "class": "form-control"}),
        label=_("Profile"),
        required=False
    )
    # --------------------------------------------------------------------
    # Education
    # edu_ecole = forms.CharField(
        # widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Ecole"}),
        # max_length=200,
        # label="Ecole"
    # )
    # edu_diplome = forms.CharField(
        # widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Diplôme"}),
        # max_length=200,
        # label="Diplôme"
    # )

    # -- Start-date, End-date
    # edu_start_date = forms.DateField(
        # widget=forms.DateInput(attrs={'type': 'date', "class": "form-control"}),
        # label="Start Date", required=False)

    # edu_end_date = forms.DateField(
        # widget=forms.DateInput(attrs={"class": "form-control", 'type': 'date'}), label="End Date", required=False)

    # -- Ville, Description
    # edu_ville = forms.CharField(
        # widget=forms.TextInput(attrs={"class": "form-control", "list": "detailsVille", "placeholder": "Ville"}),
        # max_length=200, label="Ville", required=False)

    # edu_description = forms.CharField(
        # widget=forms.Textarea(attrs={
            # 'placeholder': 'Par exemple: diplôme avec mention trés bien.',
            # "rows": 5,
            # "class": "form-control"
        # }),
        # label="Déscription",
        # required=False
    # )
    # ---------------------------------------------------------------------
    # Experience fields
    # exp_post_title = forms.CharField(
        # widget=forms.TextInput(attrs={'placeholder': 'Poste Title', "class": "form-control"}),
        # max_length=200,
        # label="Titre du post"
    # )
    # exp_employee = forms.CharField(
        # widget=forms.TextInput(attrs={'placeholder': 'Employee', "class": "form-control"}),
        # max_length=200,
        # label="Employer"
    # )
    # exp_start_date = forms.DateField(
        # widget=forms.DateInput(attrs={'type': 'date', "class": "form-control"}),
        # label="Start Date",
        # required=False
    # )
    # exp_end_date = forms.DateField(
        # widget=forms.DateInput(attrs={'type': 'date', "class": "form-control"}),
        # label="End Date",
        # required=False
    # )

    # exp_ville = forms.CharField(
        # widget=forms.TextInput(attrs={'placeholder': 'Ville', "class": "form-control"}),
        # max_length=200,
        # label="Ville",
        # required=False
    # )
    # exp_description = forms.CharField(
        # widget=forms.Textarea(attrs={
            # "placeholder": "Inclure 2 ou 3 phrases claires au sujet de votre expérience globale.",
            # "rows": 5,
            # "class": "form-control"
        # }),
        # label="Description",
        # required=False,
    # )

resumes/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from django.contrib.staticfiles import finders
from django.conf import settings
from weasyprint import HTML, CSS
from .forms import CVForm
from pathlib import Path
from . import ai_functions as ai


def ai_profile(request):
    if request.method == "POST":
        job_title = request.POST.get('job_title')
        if not job_title:
            return JsonResponse({'status': 'error', 'message': 'Job title is required'})

        result = ai.generate_profile(job_title)
        return JsonResponse(result)


def ai_education_description(request):
    if request.method == 'POST':
        diploma = request.POST.get('diploma')
        if not diploma or len(diploma) < 1:
            return JsonResponse({'status': 'error', 'message': 'diploma input is required'})
        result = ai.generate_education_description(diploma)
        return JsonResponse(result)


def ai_experience_description(request):
    if request.method == 'POST':
        job_title = request.POST.get('job_title')
        if not job_title or len(job_title) < 1:
            return JsonResponse({'status': 'error', 'message': 'Job Title input is required'})
        result = ai.generate_experience_description(job_title)
        return JsonResponse(result)


def get_skills_ai(request):
    if request.method == "POST":
        job_title = request.POST.get('job_title')
        if not job_title or len(job_title) < 1:
            return JsonResponse({'status': 'error', 'message': 'Job title is required'})

        result = ai.generate_skills(job_title)
        return JsonResponse(result)


# ==============
# Form Handle
# =============
def formate_date_fields(date):
    from datetime import datetime
    if date == '':
        return
    return datetime.strptime(date, '%Y-%m-%d').strftime('%m/%Y')


def handle_uploaded_image(profile_image):
    """Handle saving the uploaded profile image and return its path."""
    if profile_image:
        profile_image_path = Path(settings.MEDIA_ROOT) / profile_image.name
        try:
            with open(profile_image_path, 'wb+') as f:
                for chunk in profile_image.chunks():
                    f.write(chunk)

            # return profile_image_path
            profile_image_url = Path(settings.MEDIA_URL) / profile_image.name
            return profile_image_url
        except Exception as e:
            print(f"Error saving image: {e}")
    return None


def extract_languages(request):
    """Extract language proficiency data from the request."""
    languages = []
    for key in request.POST:
        if key.startswith("languages_"):
            language_index = key.split("_")[1]
            language = request.POST.get(f"languages_{language_index}")
            proficiency = request.POST.get(f"proficiency_{language_index}")
            if language:
                languages.append({'language': language, 'proficiency': int(proficiency) * "★"})
    return languages


def extract_skills(request):
    """Extract skill data from the request."""
    skills = []
    for key in request.POST:
        if key.startswith("skills_") and not key.endswith("_niveau"):
            skill_index = key.split("_")[1]
            skill = request.POST.get(f"skills_{skill_index}")
            niveau = request.POST.get(f"niveau_{skill_index}")
            if skill and niveau:
                skills.append({'skill': skill, 'niveau': niveau})
    return skills


def extract_links(request):
    """Extract link data from the request."""
    links = []
    for key in request.POST:
        if key.startswith("link_name_"):
            link_index = key.split("_")[2]
            link_name = request.POST.get(f"link_name_{link_index}")
            link_url = request.POST.get(f"link_url_{link_index}")
            if link_name and link_url:
                links.append({'name': link_name, 'url': link_url})
    return links


def extract_education(request):
    """Extract experience data from the request."""
    educations = []
    for key in request.POST:
        if key.startswith("edu_ecole"):
            edu_index = key.split("_")[-1]  # Extract experience index
            edu_ecole = request.POST.get(f"edu_ecole_{edu_index}", "")
            edu_diplome = request.POST.get(f"edu_diplome_{edu_index}", "")
            edu_start_date = request.POST.get(f"edu_start_date_{edu_index}", "")
            edu_end_date = request.POST.get(f"edu_end_date_{edu_index}", "")
            edu_ville = request.POST.get(f"edu_ville_{edu_index}", "")
            edu_description = request.POST.get(f"edu_description_{edu_index}", "")

            edu_desc_as_list = request.POST.get(f"edu_desc_aslist_{edu_index}", "")
            if edu_desc_as_list == "1":
                edu_description = edu_description.split('\r\n')

            if edu_ecole and edu_diplome:
                educations.append({
                    'edu_ecole': edu_ecole,
                    'edu_diplome': edu_diplome,
                    'edu_start_date': formate_date_fields(edu_start_date),
                    'edu_end_date': formate_date_fields(edu_end_date),
                    'edu_ville': edu_ville,
                    'edu_description': edu_description
                })
    return educations


def extract_experience(request):
    """Extract experience data from the request."""
    experiences = []
    for key in request.POST:
        if key.startswith("exp_post_title"):
            exp_index = key.split("_")[-1]  # Extract experience index
            exp_post_title = request.POST.get(f"exp_post_title_{exp_index}", "")
            exp_employee = request.POST.get(f"exp_employee_{exp_index}", "")
            exp_start_date = request.POST.get(f"exp_start_date_{exp_index}", "")
            exp_end_date = request.POST.get(f"exp_end_date_{exp_index}", "")
            exp_ville = request.POST.get(f"exp_ville_{exp_index}", "")
            exp_description = request.POST.get(f"exp_description_{exp_index}", "")

            exp_desc_as_list = request.POST.get(f"exp_desc_aslist_{exp_index}", "")
            if exp_desc_as_list == "1":
                exp_description = exp_description.split('\r\n')

            if exp_post_title and exp_employee:
                experiences.append({
                    'exp_post_title': exp_post_title,
                    'exp_employee': exp_employee,
                    'exp_start_date': formate_date_fields(exp_start_date),
                    'exp_end_date': formate_date_fields(exp_end_date),
                    'exp_ville': exp_ville,
                    'exp_description': exp_description
                })
    return experiences


def create_cv(request):
    """Handle CV form submission and generate a PDF."""
    if request.method == 'POST':
        form = CVForm(request.POST, request.FILES)

        if form.is_valid():
            form_data = form.cleaned_data
            print('-' * 100)
            print(request.POST)
            print('*' * 100)
            full_name = f"{form_data['first_name']} {form_data['last_name']}"

            # Handle Image Upload
            profile_image_path = handle_uploaded_image(form_data.get('profile_image'))
            form_data['profile_image_url'] = profile_image_path
            # form_data['profile_image_url'] = request.build_absolute_uri(profile_image_path)

            # Extract form data
            form_data['languages'] = extract_languages(request)
            form_data['skills'] = extract_skills(request)
            form_data['links'] = extract_links(request)
            form_data['experiences'] = extract_experience(request)
            form_data['educations'] = extract_education(request)

            print('-' * 100)
            for key, value in form_data.items():
                print(key)
                print('-' * len(key))
                print(value)
                print('-' * 100)

            # Select Template and CSS file
            selected_template = request.POST.get("selected_template", "simple_template.html")
            if selected_template == '':
                selected_template = 'simple_template.html'

            elif selected_template == 'simple_template.html':
                css_url = finders.find('resumes/css/simple.css')

            elif selected_template == 'bleu_template.html':
                css_url = finders.find('resumes/css/cv_template.css')

            elif selected_template == 'grey_template.html':
                css_url = finders.find('resumes/css/grey_template.css')

            elif selected_template == 'new_york.html':
                css_url = finders.find('resumes/css/new_york.css')

            cv_template = f"resumes/{selected_template}"
            output_type = request.POST.get('output_type', 'view')

            if output_type == 'pdf':
                # Render PDF
                html_string = render_to_string(cv_template, {"data": form_data})
                css = CSS(filename=css_url)
                pdf_file = HTML(string=html_string).write_pdf(stylesheets=[css])

                # Clean up temporary image file
                if profile_image_path and profile_image_path.exists():
                    profile_image_path.unlink()

                # Return the PDF as a downloadable file
                response = HttpResponse(pdf_file, content_type="application/pdf")
                response['Content-Disposition'] = f"attachment; filename=CV_{full_name}.pdf"
                return response

            else:
                # render for view
                return render(request, cv_template, {"data": form_data})
    else:
        form = CVForm()

    templates = [
        # Template for the Idea of this project
        {
            "filename": "bleu_template.html",
            "name": "Project Idea Template CV",
            "image_url": "/static/images/bleu_template.png"
        },
        # Simple Template
        {

resumes/templates/base.html
{% load i18n %}
{% load static %}
{% comment %}{% load compress %}{% endcomment %}
{% comment %}{% load humanize %}{% endcomment %}

<!DOCTYPE html>
<html data-bs-theme="light">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    {% comment %}
    {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static "base.scss" %}">
    {% endcompress %}
    {% endcomment %}

    <link rel="stylesheet" href="{% static "resumes/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "resumes/css/bootstrap-icons.min.css" %}">
    <link rel="stylesheet" href="{% static "resumes/css/form_style.css" %}">
</head>

<body>

    <!-- navbar  -->
    <nav class="navbar navbar-expand-lg border-bottom border-body bg-body-tertiary">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a 
                            class="nav-link {% if navbar == "resumes" %}active{% endif %}" aria-current="page" 
                            href="{% url "Resumes:create_cv" %}">
                            <i class="bi bi-person-lines-fill"></i>
                            CV Builder
                        </a>
                    </li>
                    <!-- Letters -->
                    <li class="nav-item">
                        <a 
                            class="nav-link {% if navbar == "letters" %}active{% endif %}" aria-current="page" 
                            href="{% url "Letters:create_letters" %}">
                            <i class="bi bi-envelope-fill"></i>
                            Create Letters
                        </a>
                    </li>
                </ul>
                <span class="navbar-text">
                    <button id="dark-theme" class="btn btn-sm btn-light"><i class="bi bi-moon-stars-fill"></i></button>
                </span>
          
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                <div class="dropdown ms-5">
                    <a class="dropdown-toggle nav-link" href="#" role="button" data-bs-toggle="dropdown" 
                       aria-expanded="false">
                        <i class="bi bi-translate me-2"></i>
                        Languages
                    </a>
          
                    <ul class="dropdown-menu dropdown-menu-end">
                        {% for language in languages%}
                        <li>
                            <a class="dropdown-item {% if language.code == LANGUAGE_CODE %}active{% endif %}" 
                               href="/{{ language.code }}/resumes/create">
                                {{ language.name_local }}
                            </a>
                        </li>
                        {% endfor %}
                        {% comment %}<li><a class="dropdown-item" href="#">Log-out</a></li>{% endcomment %}
                        {% comment %}<li><hr class="dropdown-divider"></li>{% endcomment %}
                    </ul>
                </div>

            </div>
        </div>
    </nav>
    <!------------ END NAVBAR  ------------->

    <div class="container">
        {% block content %}
        {% endblock %}

        <!-- Modal -->
        <div id="my-modal"class="modal" tabindex="-1">
            <div class="modal-dialog">
                <div id="modal-content"class="modal-content">
                    <div id="modal-header" class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div id="modal-body" class="modal-body">
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                <!-- Modal content -->
            </div>
        </div>
        <!-- End Modal -->
    </div>
    <!-- end container -->

    <!-- Bootstrap popper and jQuery and the main custom scripts-->
    <script src='{% static "resumes/js/jQuery-3.7.1.js" %}'></script>
    <script src='{% static "resumes/js/bootstrap.bundle.min.js" %}'></script>
    <script src='{% static "resumes/js/main.js" %}'></script>

</body>

</html>